<a href="https://colab.research.google.com/github/GallardoFanchinThiago/Universidad/blob/main/05_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sesión 5: Análisis de Datos con Pandas

En esta sesión, daremos el paso hacia el análisis de datos estructurados en formato tabular utilizando **Pandas**, la biblioteca estándar de Python para ciencia de datos. Aprenderás a:
* Trabajar con estructuras unidimensionales (`Series`) y bidimensionales (`DataFrame`).
* Cargar y explorar archivos de datos externos (CSV).
* Filtrar filas y calcular estadísticas descriptivas básicas.

## Recursos Oficiales de Pandas

Para profundizar en el uso de la biblioteca Pandas, puedes consultar los siguientes enlaces oficiales:

* [Documentación Oficial de Pandas](https://pandas.pydata.org/docs/)
* [Tutorial de Introducción: Getting Started](https://pandas.pydata.org/docs/getting_started/index.html)
* [Guía de Usuario de Pandas](https://pandas.pydata.org/docs/user_guide/index.html)

## 1. Introducción a DataFrames
Un `DataFrame` representa una tabla de datos similar a una hoja de cálculo, donde cada columna puede tener un tipo de dato diferente.

In [ ]:
import pandas as pd

# Crear un DataFrame desde un diccionario
datos = {
    'Ciudad': ['Buenos Aires', 'Córdoba', 'Mendoza', 'Rosario'],
    'Temperatura': [24.5, 21.2, 19.8, 22.1],
    'Lluvia': [True, False, False, True]
}
df = pd.DataFrame(datos)
display(df)

         Ciudad  Temperatura  Lluvia
0  Buenos Aires         24.5    True
1       Córdoba         21.2   False
2       Mendoza         19.8   False
3       Rosario         22.1    True

## 2. Lectura y Análisis de Datos Meteorológicos
En la carpeta del curso contamos con el archivo `'datos_basicos.csv'`. Vamos a cargarlo y realizar análisis exploratorio básico.

In [ ]:
import os
from google.colab import drive
import pandas as pd

# ==========================================
# EXPLICACIÓN: CÓMO MONTAR GOOGLE DRIVE
# ==========================================
# 1. Para acceder a tus archivos guardados en Google Drive desde Colab,
#    debes "montar" tu unidad ejecutando: drive.mount('/content/drive')
# 2. Al ejecutarlo, Colab te solicitará permisos para acceder a tu cuenta.
# 3. Una vez montado, la ruta raíz de tu unidad de Drive será:
#    '/content/drive/My Drive/' (o '/content/drive/MyDrive/')
#
# LECTURA Y ESCRITURA DE ARCHIVOS:
# - Lectura: df = pd.read_csv('/content/drive/MyDrive/ruta/al/archivo.csv')
# - Escritura: df.to_csv('/content/drive/MyDrive/ruta/al/archivo_nuevo.csv', index=False)
# ==========================================

# Montar Google Drive
drive.mount('/content/drive', force_remount=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Definimos la ruta al archivo dentro de Google Drive (o la ruta local del entorno actual)
#ruta_csv = '/content/notebooks_introduccion/datos_basicos.csv'

# Si tienes el archivo en Google Drive, puedes cambiar la ruta anterior por:
ruta_csv = "/content/drive/MyDrive/大学/IA_Meteorologia/datos/datos_basicos.csv"
#'/content/drive/MyDrive/notebooks_introduccion/datos_basicos.csv'

if os.path.exists(ruta_csv):
    df_clima = pd.read_csv(ruta_csv)
    print('Datos cargados correctamente. Primeras filas:')
    display(df_clima.head())
else:
    print(f'No se encontró el archivo en la ruta especificada: {ruta_csv}')
    print('Por favor, asegúrate de colocar el archivo en la ruta correcta de Google Drive.')

Datos cargados correctamente. Primeras filas:

,Fecha,Estacion,Temperatura_Max,Temperatura_Min,Precipitacion_mm,Humedad_Relativa
0,2023-01-01,Estacion_A_Aeroparque,23.973713,13.849756,0.000000,57.926035
1,2023-01-02,Estacion_A_Aeroparque,16.575631,9.011099,0.000000,48.863897
2,2023-01-03,Estacion_A_Aeroparque,26.580359,19.398382,0.000000,41.687345
3,2023-01-04,Estacion_A_Aeroparque,24.656982,14.553932,0.153859,73.316227
4,2023-01-05,Estacion_A_Aeroparque,NaN,-6.135895,0.000000,72.328538

In [ ]:
enlace = ("https://raw.githubusercontent.com/DanielBerns/python_para_universitarios/refs/heads/main/curso_c/notebooks_introduccion/datos/datos_basicos.csv")
try:
    df_clima = pd.read_csv(enlace)
    display(df_clima.head())
except:
    print("Error")

,Fecha,Estacion,Temperatura_Max,Temperatura_Min,Precipitacion_mm,Humedad_Relativa
0,2023-01-01,Estacion_A_Aeroparque,23.973713,13.849756,0.000000,57.926035
1,2023-01-02,Estacion_A_Aeroparque,16.575631,9.011099,0.000000,48.863897
2,2023-01-03,Estacion_A_Aeroparque,26.580359,19.398382,0.000000,41.687345
3,2023-01-04,Estacion_A_Aeroparque,24.656982,14.553932,0.153859,73.316227
4,2023-01-05,Estacion_A_Aeroparque,NaN,-6.135895,0.000000,72.328538

## 3. Prácticas
Aplica técnicas de análisis de datos para responder preguntas sobre el clima.

### Consigna 5.1: Análisis Exploratorio del Dataset
Utilizando el DataFrame `df_clima` cargado anteriormente, completa el código para calcular:
1. La temperatura promedio máxima (columna `'temperatura_max'`) y guárdala en la variable `temp_max_promedio`.
2. Filtra el DataFrame para obtener únicamente los registros donde la precipitación (columna `'precipitacion'`) sea estrictamente mayor a 10 mm. Guarda este DataFrame filtrado en la variable `df_lluvia_intensa`.

In [ ]:
#import pandas as pd
#ruta_csv = '/content/notebooks_introduccion/datos_basicos.csv'
#df_clima = pd.read_csv(ruta_csv)

# TU CÓDIGO AQUÍ:
# 1. Calcula el promedio de la columna 'temperatura_max'
temp_max_promedio = df_clima['Temperatura_Max'].mean()

# 2. Filtra las filas donde 'precipitacion' > 10.0
df_lluvia_intensa = df_clima[df_clima['Precipitacion_mm'] > 10.0]

print(f'Temperatura máxima promedio: {temp_max_promedio:.2f}°C')
print(f'Cantidad de registros con lluvia intensa: {len(df_lluvia_intensa)}')

Temperatura máxima promedio: 19.85°C
Cantidad de registros con lluvia intensa: 2

In [ ]:
# CELDA DE VERIFICACIÓN
try:
    assert 'temp_max_promedio' in globals(), 'La variable temp_max_promedio no está definida.'
    assert 'df_lluvia_intensa' in globals(), 'La variable df_lluvia_intensa no está definida.'
    assert abs(temp_max_promedio - 22.85) < 1.0, f'El promedio calculado ({temp_max_promedio:.2f}) difiere del esperado.'
    assert isinstance(df_lluvia_intensa, pd.DataFrame), 'df_lluvia_intensa debe ser un DataFrame de Pandas.'
    assert (df_lluvia_intensa['precipitacion'] > 10.0).all(), 'El filtro contiene registros con precipitaciones menores o iguales a 10 mm.'
    print('Consigna 5.1 (Análisis de datos con Pandas) completado de forma impecable. 🐼')
except AssertionError as e:
    print(f'Error de validación: {e}')

Error de validación: El promedio calculado (19.85) difiere del esperado.

### Consigna Práctica 5.2

Utilizando el DataFrame `df_clima`, realiza las siguientes tareas:
1. Filtra las filas donde la temperatura máxima (`'temperatura_max'`) sea superior a 25°C.
2. De ese subconjunto filtrado, calcula el promedio de precipitación (`'precipitacion'`) e imprime el resultado.

```python
# Tu solución aquí:
# df_calido = df_clima[...]
# prom_precip_calido = ...
# print(f"Precipitación promedio en días cálidos: {prom_precip_calido:.2f} mm")
```

In [ ]:
df_calido = df_clima[df_clima['Temperatura_Max'] > 25]
print(f"Del total de {len(df_clima)} se han descontado {len(df_clima)-len(df_calido)}")
display(df_calido)

Del total de 365 se han descontado 273

,Fecha,Estacion,Temperatura_Max,Temperatura_Min,Precipitacion_mm,Humedad_Relativa
2,2023-01-03,Estacion_A_Aeroparque,26.580359,19.398382,0.000000,41.687345
9,2023-01-10,Estacion_A_Aeroparque,25.876009,19.215265,0.000000,45.682541
11,2023-01-12,Estacion_A_Aeroparque,25.040600,19.360364,0.000000,86.444062
13,2023-01-14,Estacion_A_Aeroparque,37.151553,27.068913,1.452582,69.508785
14,2023-01-15,Estacion_A_Aeroparque,36.977250,29.040049,0.000000,-999.000000
...,...,...,...,...,...,...
350,2023-12-17,Estacion_A_Aeroparque,31.257905,22.124922,0.000000,56.578602
354,2023-12-21,Estacion_A_Aeroparque,25.482321,14.860791,0.000000,81.030140
357,2023-12-24,Estacion_A_Aeroparque,25.786786,17.637396,6.285482,84.680727
358,2023-12-25,Estacion_A_Aeroparque,32.117717,26.068677,0.000000,-999.000000
363,2023-12-30,Estacion_A_Aeroparque,28.387199,19.286234,0.000000,58.783993